# Generated by Django 4.2.6 on 2023-10-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
