# Generated by Django 4.2.6 on 2023-10-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
